Implement configuration file loader
SofairOfficial/sleppa pull request #6
Opened 2023-04-18 16:10 UTC by GuiBL4

## Description

This PR implements a configuration file loader reading a `sleppa.toml` file.

## Related issues

closes #2 

## How has this been tested?

The crate contains unit tests in the file `tests.rs`.

**Test configuration**:
* Firmware version: Ubuntu 22.10
* Hardware: Intel i5-5200U, 4.0GiB RAM
* Toolchain: `Rust cargo test`
* SDK: -

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-04-19 08:03 UTC, binadamu-isiyoonekana requested changes

2023-04-19 08:03 UTC, binadamu-isiyoonekana commented on crates/sleppa_config_parser/src/lib.rs
> +    pub fn sofair() -> Self {
I would prefer an other name. Like DefaultParser

2023-04-19 08:03 UTC, binadamu-isiyoonekana commented on crates/sleppa_config_parser/src/lib.rs
> +    fn fail_missing_field_sleppatoml() {
put test_ prefix in front of test functions

2023-04-19 08:03 UTC, binadamu-isiyoonekana commented on sleppa.toml
> +# This configuration file defines the release rules according to release types.
You should put this sample file in a specific folder called `samples`, to show that it's not a production-ready one.

Take a look for instance to the 12 Factor concepts: https://12factor.net/config

2023-04-24 07:15 UTC, binadamu-isiyoonekana requested changes

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// `Configuration` structure
/// Configuration structure

no need to put `Configuration`

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// Implementation of the `default` method : `Configuration::default()`
You can perhaps simply add #[derive(Default)] to line 62 and the Default trait will be derived automatically (as you're only initializing a HashMap

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// `ReleaseRule` structure
Same as line 56

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// `ReleaseRuleValidator` trait
Same as line 56

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// Trait to implement to to validate the [`ReleaseRule`] over a generic `format` F.
- Typo in the text (i.e. double 'to')
- Better [ReleaseRule] (no need back quotes)

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    type F;
Add a comment here (as it is easer to figure out immediately what the type is supposed to represent

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// try_parser_sleppatoml function
- Not useful description
- Comment for functions must be in indicative present, like: "Tries parsing the configuration file and return an error otherwise".
- Change the name to simply 'try_parse(path: &Path)'
- Do not put `` for types. Better to put hlink with [Configuration] or [ConfigurationError] (and not [Error], by the way, if you read carefully the ConfigurationResult's error type

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    let reading = fs::read_to_string(path)?;
Bad variable name -> 'content' or 'text' will be better. Reading means an action, not a state or a result.

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    println!("{:?}", config);
Must be deleted !! (no println!() in production code. Only logs)

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    // Verify the `sleppa.toml` contains the exact 3 [`ReleaseAction`] : `Major`, `Minor` and `Patch`
Verify that the ... contains a release rule for each release action types

2023-04-24 07:15 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +    let mut sleppatoml = File::create(&file_path).unwrap();
I really dislike this sleppatoml name for the variable. That's a file. So better to call it 'file'.

2023-04-24 12:06 UTC, GuiBL4 commented on crates/sleppa_configuration/src/lib.rs
> +    println!("{:?}", config);
Yes you are absolutely right.

2023-04-25 07:31 UTC, binadamu-isiyoonekana requested changes

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    /// Format using Peg syntax
/// Grammar of the release rule is defined using parsing expression grammar (PEG)

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// The new type associated with the `release_rules` section in the `sleppa.toml`.
/// Type alias used for typing release rule

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// This structure will be used to deserialize the toml into this Rust usable type.
/// Configuration data structure
///
/// This structure ....

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +        Configuration {
Replace with Configuration::default() as you're implementing the Default trait on Configuration

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    pub grammar: String,
Comment

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    /// Reads a message, compares it to a `grammar` in a `format` (Regex or Peg)
Too long. First a single subject line describing the intent of the function and in the body you can be more verbose.

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// Implementation of the trait [ReleaseRuleHandler] for [ReleaseRuleDefinition].
Not useful

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +                let re = match Regex::new(self.grammar.as_str()) {
I prefer 'regex' than 're'

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +                todo!()
unimplemented!()

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    fn handle(&self, message: &str) -> ConfigurationResult<bool> {
No need to put bool here. Use ConfigurationResult<()> instead and return only Ok(())

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// Tries parsing the `sleppa.toml` configuration file and returns a [Configuration] or
Too verbose. You are more saying the "how" than the "what"

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +fn test_ok_parser_sleppatoml() {
test_can_parse_configuration_file

'sleppatoml' means nothing, as the name of the configuration file can be something else. So you should only talk about configuration file.

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +    let tmp_dir = tempdir().unwrap();
To simplify, you can use ResultType on unit tests since Rust 2018. See:

```rust
#[test]
    fn test_flow_path_attribute() -> TestResult<()> {
        let valid_flow_path: MacroTokenStream = parse_quote!(
            #[flow(lazy)]
        );

        // Parse valid path
        parse::<Arguments>(valid_flow_path)?;

        let invalid_flow_path: MacroTokenStream = parse_quote!(
            #[invalid_path(lazy)]
        );

        // Parse invalid path
        assert!(parse::<Arguments>(invalid_flow_path).is_err());

        Ok(())
    }
```

where the ResultType looks like this:

```rust
/// Unit test result type
#[cfg(test)]
pub type TestResult<T> = std::result::Result<T, Box<dyn std::error::Error>>;
```

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +fn test_fail_missing_field_sleppatoml() {
Pleeasse... get rid of this 'sleppatoml'. As we know we're testing a [Configuration], no need to add this. `test_fail_missing_field` is enough as a test name

2023-04-25 07:31 UTC, binadamu-isiyoonekana commented on sample/sleppa.toml
> +# This configuration file defines the release rules according to release types.
according to release action types

2023-04-25 11:36 UTC, binadamu-isiyoonekana requested changes

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/Cargo.toml
> +description = "Toml configuration file loader for Sleppa"
Configuration management

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// The ReleaseRuleDefinition contains a grammar and the format associated to parse it.
/// Release rule resource

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +pub struct ReleaseRuleDefinition {
Why not only `ReleaseRule`

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    /// Verifies if a commit message matches the grammar.
/// Verifies if a commit message matches a release rule grammar.

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// Parses a configuration file and create a [Configuration]
/// Loads a configuration file given a file path name.

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    /// and returns a boolean. True if there is a match , false otherwise.
It does not return a bool. And you should better refer to the types, that is ReleaseRuleFormat::Peg and ReleaseRuleFormat::Peg. The comment will then be written as follows:

/// The given commit message is parsed using the release rule's grammar and in case it matches, the release rule
/// [ReleaseAction] is returned.

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +/// Tries parsing the `sleppa.toml` configuration file and returns a [Configuration] or
Noooooonn.... please as asked several times... get rid of this 'sleppa.toml' stuff :)

/// The given toml configuration file is loaded and parsed, and if successful, a [Configuration] is returned or a
/// [ConfigurationError] otherwise.

2023-04-25 11:36 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +    // Verify that `sleppa.toml` contains a release rule for each release action types.
Nooooonnnn

2023-04-25 12:06 UTC, GuiBL4 commented on crates/sleppa_configuration/src/lib.rs
> +pub struct ReleaseRuleDefinition {
An alias is already defined as ReleaseRules. I think a release rule contains the action type with its format and its grammar. Therefore ReleaseRuleDefinition seems ok here. What do you think ?

2023-04-25 12:13 UTC, GuiBL4 commented on crates/sleppa_configuration/src/lib.rs
> +    /// and returns a boolean. True if there is a match , false otherwise.
Ok for me. However, it returns an `Ok(())`. The type of action will be determined in another crate.

2023-04-25 12:50 UTC, binadamu-isiyoonekana requested changes

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on Cargo.toml
>  rust-version = "1.67"
1.69

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/Cargo.toml
> +tempfile = "3"
Try to set version at least with minor number, like `tempfile = { version = "^3.5.0" }`

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/Cargo.toml
> +regex = "^1.7.3"
Bump to new version -> `regex = { version = "^1.8.0" }`

Check other dependencies as well, and don't forget to try compiling from scratch again, both for dev and release, namely: 

`cargo clean & cargo build -p sleppa_configuration & cargo build -p sleppa_configuration --release`

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/error.rs
> +/// Enumerates all errors that can occur when processing a configuration file.
/// Enumerates all errors that can occur when processing a configuration

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +//! # Configuration file parser
//! Sleppa configuration management package

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/lib.rs
> +pub struct ReleaseRuleDefinition {
I prefer the name `ReleaseRule`, as we shall "move" the [ReleaseRules] type alias to a notion of Parser soon. So I suggest that we can now use `ReleaseRule`. Okay for you?

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +//! # Unit tests
//! Unit tests

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +#[test]
Don't forget to comment unit tests as well.

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +    writeln!(&mut file, "[release_rules]")?;
For instance, you can explain, here, that you're building a testing configuration file. This is what is know as the 'unit test preparation'

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on crates/sleppa_configuration/src/tests.rs
> +    let config = try_parse(&file_path)?;
And here this is the part of a unit test that is commonly called 'execution step`.

If you need to create reusable components, like the configuration file (i.e. sleppa.toml ;)), you can use "fixture". See for instance https://rustrepo.com/repo/la10736-rstest crate.

2023-04-25 12:50 UTC, binadamu-isiyoonekana commented on sample/sleppa.toml
> +# This configuration file defines the release rules according to release action types.
Put a top line like `# Sample Sleppa configuration file`and I suggest that you rename the file to `sleppa.example.toml`, so that this file does not end, as a side effect, as a production configuration.

2023-04-25 13:19 UTC, GuiBL4 commented on crates/sleppa_configuration/src/lib.rs
> +pub struct ReleaseRuleDefinition {
It's okay.

2023-04-26 05:51 UTC, merged