Implement commit message parser
SofairOfficial/sleppa pull request #7
Opened 2023-04-27 07:33 UTC by GuiBL4

## Description

Please include a summary of the changes proposed by this pull request (PR). Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related issues

Please indicate the issues affected by this PR using the correct Github [syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) and the correct keywords.

Ex:  
fix #1  
closes #3

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

**Test configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-03 12:14 UTC, binadamu-isiyoonekana requested changes

2023-05-03 12:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_commit_analyzer/src/lib.rs
> +    /// This function reads a provided message and verify if the message matches a ReleaseAction
reads a given commit message and verifies ... matches a [ReleaseAction]

2023-05-03 12:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_commit_analyzer/src/repositories/errors.rs
> +/// Error enumeration for the `repositories` module.
/// Enumerates errors that could occur when working with repositories.

2023-05-03 12:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_commit_analyzer/src/repositories/errors.rs
> +pub enum RepositoriesError {
RepositoryError

2023-05-03 12:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_commit_analyzer/src/repositories/github.rs
> +//! The [octocrab] crate is used to retrieve pull request, their inner commits and the tag since the last release
[Octocrab](https://crate.io....  to retrieve pull requests, their inner ....

2023-05-03 14:22 UTC, GuiBL4 commented on crates/sleppa_commit_analyzer/README.md
> +Therefore, each following commit will be a PR (with a valid name) containing inner commits.
A picture is already included int the `View of a squashed PR with inner commits` section.

2023-05-09 06:29 UTC, binadamu-isiyoonekana approved these changes
Seems okay for me. Congrats

2023-05-09 06:35 UTC, merged