Implement release note generator plugin
SofairOfficial/sleppa pull request #9
Opened 2023-05-05 09:44 UTC by GuiBL4

## Description

This pull request implements the Sleppa changelog.
This crate aims to produce the changelog notes according to verified commits messages, writes the file CHANGELOG.md and commits this file to the repository.
If the file doesn't exist, it creates a new one at a provided path. However, if the file already exists, it appends the new release notes in a reverse chronological order : the most recent at the top of the file.

## Related issues

Closes #8 

## How has this been tested?

The crate contains unit tests in the file `tests.rs`.

**Test configuration**:
* Firmware version: Ubuntu 22.10
* Hardware: Intel i5-5200U, 4.0GiB RAM
* Toolchain: `Rust cargo test`
* SDK: -

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-05-11 06:14 UTC, binadamu-isiyoonekana requested changes

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/lib.rs
> +    /// Implementation of the `new` method : `ChangelogMap::new()`
Weird this building method. The new must be related to ChangelogPlugin only.

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/lib.rs
> +    /// Builds ChangelogPlugin from verified commits
/// Builds a new changelog plugin instance based on a given list of verified commits.

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/lib.rs
> +    fn build_from_commits(&mut self, commits: Vec<Commit>, last_tag: &str, new_tag: &str, repo_url: &str) -> &Self {
Change to `from_commits`

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/lib.rs
> +    /// Maps the commit types (the key) to a vector of commit messages (the value) for the sections
Be more precise. Like

['major', ['break(xx): ...', break(xxx): xxx'],
 'minor' ['feat(xx)', ...]]

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/lib.rs
> +    /// Writes the CHANGELOG.md file
Saves the changelog file contents to the filesystem

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/lib.rs
> +    /// Writes the changelog file from the last tag of a repository
/// Executes the main function of the changelog generator plugin

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/tests.rs
> +// Use fixture to create a reusable component
... a reusable list of commits

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/tests.rs
> +// Tests the method `build_from_commits`.
// Tests the instantiation of a new changelog generator plugin with a given list of commits.

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/tests.rs
> +// The method must return a &[ChangelogPlugin] with convenient provided fields.
I don't understand what you mean

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/tests.rs
> +// Tests the method `execute` with a new file.
You don't have an execute method. Please, Guillaume, be more precise in your comments! And be more precise in the semantics of your message. Explain what you are CONCRETELY testing, not a method, but an intent.

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/tests.rs
> +// Tests the method `execute` with an existing changelog file.
No execute method... same as before

2023-05-11 06:14 UTC, binadamu-isiyoonekana commented on crates/sleppa_changelog/src/tests.rs
> +// Unit test result type
I prefer that this type be declared in errors with #[cfg(test)]... as we've already discussed, so that to centralize all errors primitives at the same place.

2023-05-11 06:28 UTC, GuiBL4 commented on crates/sleppa_changelog/src/tests.rs
> +// The method must return a &[ChangelogPlugin] with convenient provided fields.
This comment is not really relevant here. Not relevant anymore.

2023-05-11 11:54 UTC, GuiBL4 commented on crates/sleppa_changelog/src/lib.rs
> +    fn build_from_commits(&mut self, commits: Vec<Commit>, last_tag: &str, new_tag: &str, repo_url: &str) -> &Self {
After our little chat, we decided to act as a builder, thus the `from_commits()` becomes `with_commits()`.

2023-05-15 05:14 UTC, binadamu-isiyoonekana approved these changes

2023-05-15 08:20 UTC, merged